name: closet_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6595
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.6
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  provider: ^6.1.5
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  path: ^1.9.1
  table_calendar: ^3.2.0
  image: ^4.1.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.0
  http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AIWardrobe.png"
  adaptive_icon_foreground: "assets/AIWardrobe.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/AIWardrobe.png